name: AiridaleInvUtils
main: com.vhbob.airidaleinvutils.AiridaleInvUtils
version: 1.0.3
author: Vhbob
description: An inventory utils plugin for AiridaleMC
api-version: 1.16
commands:
  SafeClearInventory:
    description: Safely clear a person's inventory
    permission: safeclear.inv
    permission-message: "§CYou do not have permission to do that!"
    usage: "§CUsage: /SafeClearInventory (player)"
    aliases: [sci, safeci]
  Junker:
    description: Open the Junker
    permission: junker.use
    permission-message: "§CYou do not have permission to do that!"
depend:
  - Vault